---
title: "Data Analysis Introduction Exercise"
---
```{r}
library(dslabs)
library(tidyverse)
```

```{r}
#help(gapminder)
str(gapminder)
#The str function was used to view the observations and variables in the dataset. 
summary(gapminder)
#The summary function was used to view the quartile values of each variable and how many 
# countries are in each region. 
class(gapminder)
#The class function was used to view the class of the data set, and it is data frame. 
```

```{r}
africadata <- gapminder %>%
    filter(continent=="Africa")
#I first loaded in the gapminder dataset and used the filter function to select rows of
# countries on the Africa continent and named the variable africadata. 
str(africadata)
summary(africadata)
#The str and summary functions were used to view the number of observations in the 
# dataset, which is 2907. 
```

```{r}
africadata_IM_LE <- africadata %>%
    select(c("infant_mortality","life_expectancy"))
#I took the africadata data set I created and selected the columns infant mortality 
# and life expectancy and named it africadata_IM_LE.
str(africadata_IM_LE)
summary(africadata_IM_LE)
#The str and summary functions were used to view the new dataset and view the two 
# variables (infant mortality and life expectancy) with 2907 observations. The median
# infant mortality is 93.40 and the median life expectancy is 53.98. 
```

```{r}
africadata_POP_LE <- africadata %>%
    select(c("population","life_expectancy"))
#I took the africadata data set I created and selected the columns population and 
# life expectancy and named it africadata_POP_LE.
str(africadata_POP_LE)
summary(africadata_POP_LE)
#The str and summary functions were used to view the new dataset and view the two 
# variables (population and life expectancy) and 2907 observations. The median 
# population is 5,570,982 and median life expectancy of 53.98. 
```

```{r}
ggplot(africadata_IM_LE, aes(infant_mortality, life_expectancy)) + 
    geom_point()
#I used the ggplot function and set infant mortality on the x axis and life expectancy 
# on the y axis from the africadata_IM_LE data frame. I also added the geom_point
# function to create a scatterplot. There is a negative relationship between life 
# expectancy and infant mortality. 
```

```{r}
ggplot(africadata_POP_LE, aes(population, life_expectancy)) + 
    geom_point() + scale_x_log10()
#I used the ggplot function and set population on the x axis and life expectancy 
# on the y axis from the africadata_POP_LE data frame. I also added the geom_point 
# function to create a scatterplot. There is a positive relationship between 
# population and infant mortality. 
```

```{r}
africadata2000 <- africadata %>% 
     filter(year=="2000")
str(africadata2000)
summary(africadata2000)
#I piped in the africadata dataset and used the filter function to only have the 
# year 2000. 
```

```{r}
ggplot(africadata2000, aes(infant_mortality, life_expectancy)) + 
    geom_point()
#I used the ggplot function with geom_point to create a scatterplot with 
# infant mortality on the x axis and life expectancy on the y axis using the 
# africadata200 dataset. There is a negative relationship between infant morality 
# and life expectancy. 
ggplot(africadata2000, aes(population, life_expectancy)) + 
    geom_point() + scale_x_log10()
#I used the ggplot function with geom_point to create a scatterplot with 
# population on the x axis and life expectancy on the y axis using the 
# africadata200 dataset. I also set the x axis on a log scale. There is a negative
# relationship between infant mortality and life expectancy. 
```

```{r}
fit1 <- lm(life_expectancy~infant_mortality, data=africadata2000)
summary(fit1)
#I used the lm function and set life expectancy as the outcome and infant 
# mortality as the predictor using the africadata2000 dataset. The results are 
# highly significant, and the negative slope indicates there is a negative 
# relationship between life expectancy and infant mortality. 
fit2 <- lm(life_expectancy~population, data=africadata2000)
summary(fit2)
#I used the lm function and set life expectancy as the outcome and population 
# as the predictor using the africadata2000 dataset. The results are highly 
# significant, and the positive slope indicates there is a positive relationship 
# between life expectancy and population. 
```